In [1]:
import numpy as np

In [2]:
arr1 = np.arange(10)

In [3]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr1.shape

(10,)

In [5]:
arr1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [6]:
arr1 # orignal form still retained

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr1 = arr1.reshape(2,5)

In [8]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
arr1.shape

(2, 5)

In [10]:
arr1 = arr1.ravel()

In [11]:
arr1.shape

(10,)

In [12]:
arr2 = np.array([[1,2,3],[3,2,1]])

In [13]:
arr2

array([[1, 2, 3],
       [3, 2, 1]])

In [14]:
arr2.shape

(2, 3)

In [15]:
arr2 = arr2.reshape(3,2)
print(arr2)

[[1 2]
 [3 3]
 [2 1]]


In [16]:
arr2 = arr2.reshape(1,6)

In [17]:
arr2

array([[1, 2, 3, 3, 2, 1]])

In [18]:
arr2 = arr2.reshape(6,1)
print(arr2)

[[1]
 [2]
 [3]
 [3]
 [2]
 [1]]


In [19]:
arr2.shape

(6, 1)

In [20]:
flat_arr = arr2.ravel()

In [21]:
flat_arr

array([1, 2, 3, 3, 2, 1])

In [22]:
flat_arr.ndim

1

In [23]:
test_arr = np.array(range(5))
test_arr

array([0, 1, 2, 3, 4])

In [24]:
test_arr = test_arr.reshape(5,1)
test_arr

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [25]:
test_arr.ndim

2

In [26]:
arr = np.array([[1], [2], [3]])

In [27]:
arr.ndim

2

In [28]:
arr.shape

(3, 1)

In [29]:
np.array([[1], [2], [3]]).shape

(3, 1)

In [30]:
np.array([[[1], [2], [3]]]).shape

(1, 3, 1)

In [31]:
np.array([[1,2]]).shape

(1, 2)

In [32]:
some_arr = np.array([[1],[2],[3]]) # an array with single column and one row

In [33]:
some_arr

array([[1],
       [2],
       [3]])

In [34]:
some_arr.ndim

2

In [35]:
some_arr.shape

(3, 1)

In [36]:
# same array taking different dimensions

In [37]:
some_arr = np.array([1,2,3])

In [38]:
some_arr.shape

(3,)

In [39]:
some_arr = np.array([[1,2,3]])

In [40]:
some_arr.shape

(1, 3)

In [41]:
some_arr = np.array([[[1,2,3]]])

In [42]:
some_arr.shape

(1, 1, 3)

In [43]:
np.array([[[1,2,3],[1,2,1],[0,1,2]]]).shape

(1, 3, 3)