In [1]:
import numpy as np

In [2]:
m1  = np.array([[2,5,1],[6,7,0],[1,4,9]])

In [3]:
m2 = np.array([[3,2,1],[1,2,0],[0,6,3]])

In [4]:
m1

array([[2, 5, 1],
       [6, 7, 0],
       [1, 4, 9]])

In [5]:
m2

array([[3, 2, 1],
       [1, 2, 0],
       [0, 6, 3]])

In [6]:
m1 + m2

array([[ 5,  7,  2],
       [ 7,  9,  0],
       [ 1, 10, 12]])

In [7]:
m1 - m2

array([[-1,  3,  0],
       [ 5,  5,  0],
       [ 1, -2,  6]])

In [8]:
m1 * m2

array([[ 6, 10,  1],
       [ 6, 14,  0],
       [ 0, 24, 27]])

In [9]:
# m1 / m2 works fine if there are no non zero elements

In [12]:
np.where(m1>4)

(array([0, 1, 1, 2]), array([1, 0, 1, 2]))

In [13]:
np.sqrt(m1)

array([[1.41421356, 2.23606798, 1.        ],
       [2.44948974, 2.64575131, 0.        ],
       [1.        , 2.        , 3.        ]])

In [15]:
np.count_nonzero(m2) # returns a count of non zero elements

7

In [18]:
print(m2)

[[3 2 1]
 [1 2 0]
 [0 6 3]]


In [19]:
np.nonzero(m2) # retuns indexes of non zero elements as an array of tuples

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 1, 2]))

In [20]:
m2[0,0] = 0

In [22]:
np.nonzero(m2) # 0,0 index will dissappear now

(array([0, 0, 1, 1, 2, 2]), array([1, 2, 0, 1, 1, 2]))